export const initialState = {
  adminAccount: {
    userName: "admin",
    password: "avion123",
    name: "Patrick Nebab",
    age: 26,
    position: "Account Manager",
    accountNumber: "1234 4568",
  },
  adminUser: "admin",
  adminPassword: "avion123",
  isvalidError: false,
  validError: "",
  accountList: JSON.parse(localStorage.getItem("account")) || [],
  filteredAccount: JSON.parse(localStorage.getItem("filteredAccount")) || [],
  selectedAccount: JSON.parse(localStorage.getItem("selectedAccount")) || null,
  allTransactionHistory:
    JSON.parse(localStorage.getItem("allTransactionHistory")) || [],
  accountHolderFirstName: "",
  accountHolderLastName: "",
  accountInitialBalance: "",
  email: "",
  birthDate: "",
  password: "",
  amountWidthdraw: "",
  amountDeposit: "",
  amountLoan: "",
  receiverId: "",
  senderId: "",
  senderAmount: "",
  expenseName: "",
  editExpenseName: "",
  expenseAmount: "",
  loanTerms: "",
  searchQuery: "",
  isOpen: false,
};
