export const initialStateTransaction = {
  accountList: JSON.parse(localStorage.getItem("account")) || [],
  filteredAccount: [],
  accountHolderFirstName: "",
  accountHolderLastName: "",
  accountInitialBalance: "",
  email: "",
  birthDate: "",
  password: "",
  amountWidthdraw: "",
  amountDeposit: "",
  amountLoan: "",
  receiverId: "",
  senderId: "",
  senderAmount: "",
  expenseName: "",
  editExpenseName: "",
  expenseAmount: "",
  loanTerms: "",
  searchQuery: "",
  selectedAccount: JSON.parse(localStorage.getItem("selectedAccount")) || null,
  allTransactionHistory:
    JSON.parse(localStorage.getItem("allTransactionHistory")) || [],
  isOpen: false,
  isEdit: false,
  isaccountHolderFirstNameError: false,
  isaccountHolderLastNameError: false,
  isaccountInitialBalanceError: false,
  isemailError: false,
  isbirthDateError: false,
  isamountWidthdrawError: false,
  isamountDepositError: false,
  issenderIdError: false,
  isreceiverIdError: false,
  isssenderAmountError: false,
  isamountLoanError: false,
  isexpenseNameError: false,
  isexpenseAmountError: false,
  isApproved: false,
  isOpenApproved: false,
  isOpenDetails: false,
  issearchQueryError: false,
  searchQueryError: "",
  amountWidthdrawError: "",
  amountDepositError: "",
  amountLoanError: "",
  senderIdError: "",
  receiverIdError: "",
  senderAmountError: "",
  expenseNameError: "",
  expenseAmountError: "",
  accountHolderFirstNameError: "",
  accountHolderLastNameError: "",
  accountInitialBalanceError: "",
  birtDateError: "",
  emailError: "",
};
