export const initialStateTransaction = {
  accountList: JSON.parse(localStorage.getItem("account")) || [],
  accountHolderFirstName: "",
  accountHolderLastName: "",
  accountInitialBalance: "",
  email: "",
  birthDate: "",
  password: "",
  amountWidthdraw: "",
  amountDeposit: "",
  amountRequest: "",
  receiverId: "",
  senderId: "",
  senderAmount: "",
  expenseName: "",
  editExpenseName: "",
  expenseAmount: "",
  selectedAccount: JSON.parse(localStorage.getItem("selectedAccount")) || null,
  expenseList: [],
  allTransactionHistory: [],
  isAddAcc: false,
  isEdit: false,
  isaccountHolderFirstNameError: false,
  isaccountHolderLastNameError: false,
  isaccountInitialBalanceError: false,
  isemailError: false,
  isbirthDateError: false,
  accountHolderFirstNameError: "",
  accountHolderLastNameError: "",
  accountInitialBalanceError: "",
  birtDateError: "",
  emailError: "",
};
